stages:
  - lint
  - test
  - build
  - deploy

run_lint:
  stage: lint
  image: node:20.10.0
  before_script:
    - npm install
  allow_failure: false
  script:
    - npm run lint

run_test:
  stage: test
  before_script:
    - echo "Before running script..."
    - echo "End before script."

  script:
    - echo "Running test..."

run_image:
  stage: build
  script:
    - docker build -t vue-app .

run_deploy:
  stage: deploy
  script:
    - docker compose up -d
